# Generated by Django 6.0.5 on 2026-07-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commercial_register_doc',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/rc/', verbose_name='نسخة السجل التجاري (PDF)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_card_doc',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/tax/', verbose_name='نسخة البطاقة الجبائية (PDF)'),
        ),
    ]
