# Generated by Django 5.0.14 on 2026-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_commercial_register_doc_user_tax_card_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإدراج في القائمة السوداء'),
        ),
        migrations.AddField(
            model_name='user',
            name='blacklist_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الحظر'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='مدرج في القائمة السوداء'),
        ),
    ]
