# Generated by Django 6.0.8 on 2026-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_qrloginsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_central_dashboard', 'Can view central administration dashboard'), ('manage_all_users', 'Can manage all users and suppliers'), ('audit_all_tenders', 'Can audit all tenders system-wide'), ('view_system_reports', 'Can view system-wide reports')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('authority', 'مصلحة متعاقدة'), ('supplier', 'متعامل اقتصادي'), ('central_admin', 'إدارة مركزية')], max_length=20),
        ),
        migrations.DeleteModel(
            name='QRLoginSession',
        ),
    ]
