# Generated by Django 6.1 on 2026-08-11 12:05

from django.db import migrations

def forward_func(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Permission = apps.get_model('auth', 'Permission')
    
    # List of permissions required for central_admin
    required_permissions = [
        'view_central_dashboard',
        'manage_all_users',
        'audit_all_tenders',
        'view_system_reports',
    ]
    
    perms = Permission.objects.filter(
        codename__in=required_permissions,
        content_type__app_label='accounts'
    )
    
    # Assign them to all current central_admin users
    for user in User.objects.filter(role='central_admin'):
        user.user_permissions.add(*perms)

def reverse_func(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Permission = apps.get_model('auth', 'Permission')
    
    required_permissions = [
        'view_central_dashboard',
        'manage_all_users',
        'audit_all_tenders',
        'view_system_reports',
    ]
    
    perms = Permission.objects.filter(
        codename__in=required_permissions,
        content_type__app_label='accounts'
    )
    
    for user in User.objects.filter(role='central_admin'):
        user.user_permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options_alter_user_role_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
