# Generated by Django 6.1 on 2026-08-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_assign_central_admin_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_confidence_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="نسبة ثقة الذكاء الاصطناعي"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="capabilities",
            field=models.JSONField(
                blank=True, null=True, verbose_name="القدرات المستخرجة آلياً (AI)"
            ),
        ),
    ]
