# Generated by Django 6.1 on 2026-08-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_ai_confidence_score_user_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nif_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="رقم التعريف الجبائي (NIF)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nis_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="رقم التعريف الإحصائي (NIS)",
            ),
        ),
    ]
