# Generated by Django 6.1 on 2026-08-15 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0038_alter_historicaltender_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollusionAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("shared_ip", "تطابق عنوان IP عند الإيداع"),
                            ("shared_device", "تطابق البصمة الرقمية للجهاز / المتصفح"),
                            ("doc_metadata", "تطابق ميتاداتا الوثائق والملفات المرفقة"),
                            ("price_pattern", "نمط تسعير مشبوه / عروض تغطية متبادلة"),
                            ("submission_timing", "تزامن مريب في توقيت الإيداع"),
                        ],
                        max_length=30,
                        verbose_name="نوع الشبهة",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "مرتفع / حرج"),
                        ],
                        default="medium",
                        max_length=15,
                        verbose_name="درجة الخطورة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد قيد الفحص"),
                            ("under_investigation", "قيد التحقيق الرقابي"),
                            ("confirmed", "تم تأكيد الشبهة"),
                            ("dismissed", "تم الحفظ / مبرر قانونياً"),
                        ],
                        default="new",
                        max_length=25,
                        verbose_name="حالة البلاغ",
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=50, verbose_name="مؤشر المخاطر (0-100)"
                    ),
                ),
                (
                    "evidence_summary",
                    models.TextField(verbose_name="ملخص القرائن والأدلة الرقمية"),
                ),
                (
                    "evidence_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="البيانات التقنية التفصيلية",
                    ),
                ),
                (
                    "investigator_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات المفتش المركزي"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرصد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "involved_suppliers",
                    models.ManyToManyField(
                        related_name="collusion_flags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المتعاملون المشتبه بهم",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collusion_alerts",
                        to="procurement.tender",
                        verbose_name="الصفقة المعنية",
                    ),
                ),
            ],
            options={
                "verbose_name": "إنذار شبهة تواطؤ",
                "verbose_name_plural": "إنذارات شبهات التواطؤ",
                "ordering": ["-risk_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RFPAuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "مطابق للمعايير الوطنية"),
                            ("warning", "يتضمن قيوداً وشروطاً تتطلب المراجعة"),
                            (
                                "violating",
                                "يتضمن شروطاً تعجيزية / غير مطابقة للمرسوم 23-12",
                            ),
                        ],
                        default="compliant",
                        max_length=20,
                        verbose_name="حالة المطابقة",
                    ),
                ),
                (
                    "compliance_score",
                    models.IntegerField(
                        default=100, verbose_name="درجة الامتثال (0-100)"
                    ),
                ),
                (
                    "tailored_specs_detected",
                    models.BooleanField(
                        default=False, verbose_name="شبهة تفصيل مواصفات حصرية"
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="الملاحظات والثغرات المرصودة",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, verbose_name="توصيات لجنة الرقابة المركزية"
                    ),
                ),
                (
                    "audited_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الفحص الآلي"
                    ),
                ),
                (
                    "tender",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfp_audit",
                        to="procurement.tender",
                        verbose_name="الصفقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير تدقيق دفتر الشروط",
                "verbose_name_plural": "تقارير تدقيق دفاتر الشروط",
            },
        ),
        migrations.CreateModel(
            name="TenderRiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_risk",
                    models.IntegerField(
                        default=10, verbose_name="معدل الخطر الإجمالي (0-100)"
                    ),
                ),
                (
                    "failure_probability",
                    models.FloatField(
                        default=0.05, verbose_name="احتمالية تعثر المشروع"
                    ),
                ),
                (
                    "abnormally_low_bid_risk",
                    models.BooleanField(
                        default=False, verbose_name="خطر عروض متدنية بشكل غير طبيعي"
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="العوامل المؤثرة في المخاطر",
                    ),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تقييم"),
                ),
                (
                    "tender",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_risk_score",
                        to="procurement.tender",
                        verbose_name="الصفقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة مخاطر الصفقة",
                "verbose_name_plural": "بطاقات مخاطر الصفقات",
            },
        ),
    ]
