# Generated by Django 6.0.5 on 2026-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الصفقة')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الميزانية التقديرية (دج)')),
                ('deadline', models.DateField(verbose_name='آخر أجل للتقديم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('closed', 'مغلقة'), ('evaluating', 'قيد التقييم')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفقة',
                'verbose_name_plural': 'الصفقات',
                'ordering': ['-created_at'],
            },
        ),
    ]
