# Generated by Django 6.0.5 on 2026-07-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='اسم الشركة / المتعامل')),
                ('financial_offer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='العرض المالي (دج)')),
                ('technical_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات العرض التقني')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة العرض')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.tender', verbose_name='الصفقة')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
