# Generated by Django 6.0.5 on 2026-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tenders/documents/', verbose_name='دفتر الشروط'),
        ),
    ]
