# Generated by Django 6.0.5 on 2026-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_tender_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='موافقة وتصريح شرفي'),
        ),
        migrations.AddField(
            model_name='bid',
            name='delivery_time_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الإنجاز (بالأيام)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='nif_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التعريف الجبائي (NIF)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='nis_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التعريف الإحصائي (NIS)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='similar_projects_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المشاريع المماثلة المنجزة'),
        ),
        migrations.AddField(
            model_name='bid',
            name='technical_team_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد الطاقم التقني'),
        ),
        migrations.AddField(
            model_name='bid',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الضمان (بالأشهر)'),
        ),
    ]
