# Generated by Django 6.0.5 on 2026-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_bid_agreement_bid_delivery_time_days_bid_nif_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع النشاط'),
        ),
        migrations.AddField(
            model_name='tender',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الولاية'),
        ),
    ]
