# Generated by Django 6.0.5 on 2026-07-04 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_tender_sector_tender_wilaya'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='اسم الشركة / المتعامل')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='المراجعة والملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المصلحة المقيمة')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='procurement.tender', verbose_name='الصفقة')),
            ],
        ),
        migrations.CreateModel(
            name='TenderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='إجابة المصلحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ السؤال')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإجابة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL, verbose_name='المتعامل السائل')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='procurement.tender', verbose_name='الصفقة')),
            ],
        ),
    ]
