# Generated by Django 6.0.5 on 2026-07-04 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_supplierrating_tenderquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='document_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم سحب دفتر الشروط (دج)'),
        ),
        migrations.CreateModel(
            name='DocumentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع (دج)')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='رقم العملية')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_payments', to=settings.AUTH_USER_MODEL, verbose_name='المتعامل')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.tender', verbose_name='الصفقة')),
            ],
            options={
                'verbose_name': 'دفع دفتر الشروط',
                'verbose_name_plural': 'مدفوعات دفاتر الشروط',
                'unique_together': {('tender', 'supplier')},
            },
        ),
    ]
