# Generated by Django 6.0.5 on 2026-07-04 21:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_tender_document_fee_documentpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBid',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='اسم الشركة / المتعامل')),
                ('nif_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التعريف الجبائي (NIF)')),
                ('nis_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التعريف الإحصائي (NIS)')),
                ('financial_offer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='العرض المالي (دج)')),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الإنجاز (بالأيام)')),
                ('warranty_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الضمان (بالأشهر)')),
                ('technical_team_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد الطاقم التقني')),
                ('similar_projects_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='المشاريع المماثلة المنجزة')),
                ('technical_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات العرض التقني')),
                ('agreement', models.BooleanField(default=False, verbose_name='موافقة وتصريح شرفي')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة العرض')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.tender', verbose_name='الصفقة')),
            ],
            options={
                'verbose_name': 'historical عرض',
                'verbose_name_plural': 'historical العروض',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTender',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الصفقة')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الميزانية التقديرية (دج)')),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='الولاية')),
                ('sector', models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع النشاط')),
                ('deadline', models.DateField(verbose_name='آخر أجل للتقديم')),
                ('document', models.TextField(blank=True, max_length=100, null=True, verbose_name='دفتر الشروط')),
                ('document_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم سحب دفتر الشروط (دج)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('closed', 'مغلقة'), ('evaluating', 'قيد التقييم')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical صفقة',
                'verbose_name_plural': 'historical الصفقات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
