# Generated by Django 6.0.5 on 2026-07-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_historicalbid_historicaltender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='financial_document',
            field=models.FileField(blank=True, null=True, upload_to='bids/financial/', verbose_name='ملف العرض المالي (PDF)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='integrity_declaration',
            field=models.FileField(blank=True, null=True, upload_to='bids/integrity/', verbose_name='التصريح بالنزاهة (PDF)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='technical_document',
            field=models.FileField(blank=True, null=True, upload_to='bids/technical/', verbose_name='ملف العرض التقني (PDF)'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='financial_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='ملف العرض المالي (PDF)'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='integrity_declaration',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='التصريح بالنزاهة (PDF)'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='technical_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='ملف العرض التقني (PDF)'),
        ),
    ]
