# Generated by Django 5.0.14 on 2026-07-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_historicaltender_authority_tender_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='البصمة المشفرة (Hash)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم معاملة البلوكتشين (TxHash)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_blockchain_verified',
            field=models.BooleanField(default=False, verbose_name='موثق عبر البلوكتشين'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='bid_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='البصمة المشفرة (Hash)'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم معاملة البلوكتشين (TxHash)'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='is_blockchain_verified',
            field=models.BooleanField(default=False, verbose_name='موثق عبر البلوكتشين'),
        ),
    ]
