# Generated by Django 5.0.14 on 2026-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_bid_bid_hash_bid_blockchain_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bank_guarantee_file',
            field=models.FileField(blank=True, null=True, upload_to='bids/guarantees/', verbose_name='كفالة التعهد البنكية (PDF)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='البنك الضامن'),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_guarantee_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من الكفالة'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='bank_guarantee_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='كفالة التعهد البنكية (PDF)'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='البنك الضامن'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='is_guarantee_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من الكفالة'),
        ),
    ]
