# Generated by Django 5.0.14 on 2026-07-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_bid_bank_guarantee_file_bid_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='مضمون الطعن')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='appeals/docs/', verbose_name='الملف المرفق للطعن (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تقديم الطعن')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة'), ('accepted', 'مقبول (مؤسس)'), ('rejected', 'مرفوض (غير مؤسس)')], default='pending', max_length=20, verbose_name='حالة الطعن')),
                ('authority_response', models.TextField(blank=True, null=True, verbose_name='رد المصلحة المتعاقدة')),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='procurement.bid', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'طعن',
                'verbose_name_plural': 'الطعون',
            },
        ),
    ]
