# Generated by Django 5.0.14 on 2026-07-06 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_tenderappeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_committee', models.CharField(default='عضو مقيّم', max_length=100, verbose_name='الصفة في اللجنة (رئيس، عضو، مقرر)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='procurement.tender', verbose_name='الصفقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_roles', to=settings.AUTH_USER_MODEL, verbose_name='عضو اللجنة')),
            ],
            options={
                'verbose_name': 'عضو لجنة التقييم',
                'verbose_name_plural': 'أعضاء لجان التقييم',
                'unique_together': {('tender', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ وتوقيت المصادقة')),
                ('signature_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='البصمة الرقمية للتوقيع (Hash)')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='procurement.committeemember', verbose_name='عضو اللجنة')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='procurement.tender', verbose_name='الصفقة')),
            ],
            options={
                'verbose_name': 'توقيع التقييم',
                'verbose_name_plural': 'تواقيع التقييم',
                'unique_together': {('tender', 'committee_member')},
            },
        ),
    ]
