# Generated by Django 5.0.14 on 2026-07-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_committeemember_evaluationsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltender',
            name='tender_type',
            field=models.CharField(choices=[('open', 'طلب عروض مفتوح'), ('national', 'طلب عروض وطني'), ('national_international', 'طلب عروض وطني ودولي'), ('consultation', 'استشارة'), ('mutual', 'بالتراضي')], default='open', max_length=50, verbose_name='نوع الصفقة'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type',
            field=models.CharField(choices=[('open', 'طلب عروض مفتوح'), ('national', 'طلب عروض وطني'), ('national_international', 'طلب عروض وطني ودولي'), ('consultation', 'استشارة'), ('mutual', 'بالتراضي')], default='open', max_length=50, verbose_name='نوع الصفقة'),
        ),
    ]
