# Generated by Django 5.0.14 on 2026-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_alter_historicaltender_tender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltender',
            name='tender_type',
            field=models.CharField(choices=[('open', 'طلب العروض المفتوح'), ('minimum_capacity', 'طلب العروض مع اشتراط قدرات دنيا'), ('restricted', 'طلب العروض المحدود'), ('contest', 'المسابقة'), ('negotiation', 'التفاوض'), ('mutual', 'بالتراضي')], default='open', max_length=50, verbose_name='نوع الصفقة'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_type',
            field=models.CharField(choices=[('open', 'طلب العروض المفتوح'), ('minimum_capacity', 'طلب العروض مع اشتراط قدرات دنيا'), ('restricted', 'طلب العروض المحدود'), ('contest', 'المسابقة'), ('negotiation', 'التفاوض'), ('mutual', 'بالتراضي')], default='open', max_length=50, verbose_name='نوع الصفقة'),
        ),
    ]
