# Generated by Django 6.1 on 2026-08-07 10:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_historicaltender_ai_cahier_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltender',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltender',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف؟'),
        ),
        migrations.AddField(
            model_name='tender',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف؟'),
        ),
        migrations.AlterField(
            model_name='historicaltender',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الميزانية التقديرية (دج)'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الميزانية التقديرية (دج)'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status', 'created_at'], name='procurement_status_bc82e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['wilaya', 'sector'], name='procurement_wilaya_e62f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['is_deleted'], name='procurement_is_dele_953855_idx'),
        ),
    ]
