# Generated by Django 6.1 on 2026-08-07 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_historicaltender_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة المالية')),
                ('sector', models.CharField(max_length=255, verbose_name='القطاع')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الميزانية الإجمالية (دج)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='المصلحة المتعاقدة')),
            ],
            options={
                'verbose_name': 'ميزانية سنوية',
                'verbose_name_plural': 'الميزانيات السنوية',
                'unique_together': {('year', 'sector', 'authority')},
            },
        ),
        migrations.CreateModel(
            name='PlannedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم المشروع المبرمج')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='القيمة التقديرية (دج)')),
                ('expected_launch_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإطلاق المتوقع')),
                ('is_launched', models.BooleanField(default=False, verbose_name='تم الإطلاق (تحول إلى صفقة)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_projects', to='procurement.annualbudget', verbose_name='الميزانية المرتبطة')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_planned_project', to='procurement.tender', verbose_name='الصفقة الفعلية المرتبطة')),
            ],
            options={
                'verbose_name': 'مشروع مبرمج',
                'verbose_name_plural': 'المشاريع المبرمجة',
            },
        ),
    ]
