# Generated by Django 6.1 on 2026-08-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_annualbudget_plannedproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOpeningCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ وساعة الفتح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المحضر')),
                ('is_valid', models.BooleanField(default=True, verbose_name='محضر صالح')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رئيس الجلسة')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_committee', to='procurement.tender', verbose_name='الصفقة')),
            ],
            options={
                'verbose_name': 'محضر لجنة الفتح',
                'verbose_name_plural': 'محاضر لجان الفتح',
            },
        ),
    ]
