# Generated by Django 6.1 on 2026-08-07 22:56

import apps.procurement.models
import apps.procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_bidopeningcommittee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bank_guarantee_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.procurement.models.secure_upload_path, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='كفالة التعهد البنكية (PDF)'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='financial_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.procurement.models.secure_upload_path, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='ملف العرض المالي (PDF)'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='integrity_declaration',
            field=models.FileField(blank=True, null=True, upload_to=apps.procurement.models.secure_upload_path, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='التصريح بالنزاهة (PDF)'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='technical_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.procurement.models.secure_upload_path, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='ملف العرض التقني (PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalbid',
            name='bank_guarantee_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='كفالة التعهد البنكية (PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalbid',
            name='financial_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='ملف العرض المالي (PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalbid',
            name='integrity_declaration',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='التصريح بالنزاهة (PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalbid',
            name='technical_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.procurement.validators.validate_file_mimetype], verbose_name='ملف العرض التقني (PDF)'),
        ),
    ]
