# Generated by Django 6.1 on 2026-08-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_alter_bid_bank_guarantee_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف؟'),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbid',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف؟'),
        ),
    ]
