# Generated by Django 6.1 on 2026-08-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_bid_deleted_at_bid_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidopeningcommittee',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='bids/reports/', verbose_name='ملف المحضر (PDF)'),
        ),
    ]
