# Generated by Django 6.1 on 2026-08-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_bidopeningcommittee_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltender',
            name='is_bids_opened',
            field=models.BooleanField(default=False, verbose_name='تم فتح العروض'),
        ),
        migrations.AddField(
            model_name='tender',
            name='is_bids_opened',
            field=models.BooleanField(default=False, verbose_name='تم فتح العروض'),
        ),
    ]
