# Generated by Django 6.1 on 2026-08-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0027_bid_supplier_historicalbid_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidopeningcommittee',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='محضر نهائي معتمد'),
        ),
        migrations.AddField(
            model_name='bidopeningcommittee',
            name='report_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بصمة المحضر (SHA-256)'),
        ),
        migrations.AddField(
            model_name='bidopeningcommittee',
            name='report_version',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الإصدار'),
        ),
    ]
