# Generated by Django 6.1 on 2026-08-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0029_alter_bid_ai_evaluation_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualbudget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "قيد المراجعة"),
                    ("approved", "معتمدة"),
                    ("rejected", "مرفوضة"),
                ],
                default="draft",
                max_length=20,
                verbose_name="حالة الخطة",
            ),
        ),
    ]
