# Generated by Django 6.1 on 2026-08-12 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0030_annualbudget_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإسناد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("published", "منشور"),
                            ("canceled", "ملغى"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "awarded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="مبلغ الإسناد (دج)",
                    ),
                ),
                (
                    "decision_reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم قرار المنح"
                    ),
                ),
                (
                    "decision_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="awards/decisions/",
                        verbose_name="وثيقة قرار المنح",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسؤول الإسناد",
                    ),
                ),
                (
                    "tender",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award",
                        to="procurement.tender",
                        verbose_name="الصفقة",
                    ),
                ),
                (
                    "winning_bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award",
                        to="procurement.bid",
                        verbose_name="العرض الفائز",
                    ),
                ),
            ],
            options={
                "verbose_name": "إسناد",
                "verbose_name_plural": "الإسنادات",
                "ordering": ["-created_at"],
            },
        ),
    ]
