# Generated by Django 6.1 on 2026-08-12 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0031_award"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم العقد"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان العقد")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("signed", "مُوقّع"),
                            ("active", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("terminated", "مفسوخ"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التوقيع"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="القيمة الإجمالية"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="DZD", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "guarantee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="مبلغ الضمان",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُعتمد العقد",
                    ),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_as_authority",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المصلحة المتعاقدة",
                    ),
                ),
                (
                    "award",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="procurement.award",
                        verbose_name="الإسناد",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُنشئ العقد",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_as_supplier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المورد (المتعامل)",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amendment_number",
                    models.CharField(max_length=50, verbose_name="رقم الملحق"),
                ),
                (
                    "amendment_type",
                    models.CharField(
                        choices=[
                            ("value", "تعديل قيمة"),
                            ("duration", "تمديد آجال"),
                            ("both", "تعديل قيمة وتمديد آجال"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الملحق",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب التعديل")),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="القيمة السابقة",
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="القيمة الجديدة",
                    ),
                ),
                (
                    "previous_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية السابق"
                    ),
                ),
                (
                    "new_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية الجديد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "decision_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/amendments/",
                        verbose_name="وثيقة الملحق",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُعتمد",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="procurement.contract",
                        verbose_name="العقد الأساسي",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُقدم الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملحق عقد",
                "verbose_name_plural": "ملاحق العقود",
                "ordering": ["-created_at"],
                "unique_together": {("contract", "amendment_number")},
            },
        ),
    ]
