# Generated by Django 6.1 on 2026-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0032_contract_contractamendment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("proposed", "مقترح"),
                    ("under_review", "قيد المراجعة"),
                    ("approved", "معتمد"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغى"),
                ],
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("pending_signature", "قيد التوقيع"),
                    ("active", "قيد التنفيذ"),
                    ("suspended", "مُعلّق"),
                    ("completed", "مكتمل"),
                    ("terminated", "مفسوخ"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="contractamendment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُقدم"),
                    ("under_review", "قيد المراجعة"),
                    ("approved", "معتمد"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغى"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
