# Generated by Django 6.1 on 2026-08-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0033_alter_award_status_alter_contract_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="award",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("create_award_recommendation", "Can create award recommendation"),
                    ("approve_award", "Can approve award"),
                    ("reject_award", "Can reject award"),
                    ("cancel_award", "Can cancel award"),
                ],
                "verbose_name": "إسناد",
                "verbose_name_plural": "الإسنادات",
            },
        ),
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_contract", "Can approve contract"),
                    ("terminate_contract", "Can terminate contract"),
                ],
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
            },
        ),
        migrations.AlterModelOptions(
            name="contractamendment",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_contract_amendment", "Can approve contract amendment"),
                    ("reject_contract_amendment", "Can reject contract amendment"),
                ],
                "verbose_name": "ملحق عقد",
                "verbose_name_plural": "ملاحق العقود",
            },
        ),
    ]
