# Generated by Django 6.1 on 2026-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0034_alter_award_options_alter_contract_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltender",
            name="ai_executive_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملخص تنفيذي (AI)"
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="ai_executive_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملخص تنفيذي (AI)"
            ),
        ),
    ]
