# Generated by Django 6.1 on 2026-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0035_historicaltender_ai_executive_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltender",
            name="is_frozen",
            field=models.BooleanField(
                default=False, verbose_name="مجمدة (توقيف احترازي)"
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="is_frozen",
            field=models.BooleanField(
                default=False, verbose_name="مجمدة (توقيف احترازي)"
            ),
        ),
    ]
