# Generated by Django 6.1 on 2026-08-14 21:55

import apps.procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0037_procurementauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltender",
            name="deadline",
            field=models.DateTimeField(verbose_name="آخر أجل للتقديم"),
        ),
        migrations.AlterField(
            model_name="historicaltender",
            name="document",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    apps.procurement.validators.validate_file_mimetype,
                    apps.procurement.validators.validate_file_size,
                ],
                verbose_name="دفتر الشروط",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="deadline",
            field=models.DateTimeField(verbose_name="آخر أجل للتقديم"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tenders/documents/",
                validators=[
                    apps.procurement.validators.validate_file_mimetype,
                    apps.procurement.validators.validate_file_size,
                ],
                verbose_name="دفتر الشروط",
            ),
        ),
    ]
