# Generated by Django 6.1 on 2026-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0038_alter_historicaltender_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpayment",
            name="approval_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="رمز الموافقة البنكية (Approval Code)",
            ),
        ),
        migrations.AddField(
            model_name="documentpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cib", "البطاقة البنكية CIB (SATIM)"),
                    ("edahabia", "البطاقة الذهبية (بريد الجزائر)"),
                ],
                default="edahabia",
                max_length=20,
                verbose_name="وسيلة الدفع",
            ),
        ),
        migrations.AddField(
            model_name="documentpayment",
            name="receipt_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="رقم الوصل المحاسبي الرسمي",
            ),
        ),
        migrations.AddField(
            model_name="documentpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "قيد التهيئة"),
                    ("pending", "قيد المعالجة البنكية"),
                    ("completed", "مدفوع ومؤكد بنجاح"),
                    ("failed", "فشلت المعاملة"),
                    ("refunded", "مسترجع"),
                ],
                default="completed",
                max_length=20,
                verbose_name="حالة المعاملة",
            ),
        ),
        migrations.AlterField(
            model_name="documentpayment",
            name="paid_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاريخ وتوقيت الدفع"
            ),
        ),
        migrations.AlterField(
            model_name="documentpayment",
            name="transaction_id",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="رقم العملية البنكية (Order ID)",
            ),
        ),
    ]
