# Generated by Django 6.1 on 2026-08-15 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0039_documentpayment_approval_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annualbudget",
            options={
                "verbose_name": "مخطط تقديري سنوي",
                "verbose_name_plural": "المخططات التقديرية السنوية",
            },
        ),
        migrations.AlterModelOptions(
            name="plannedproject",
            options={
                "ordering": ["estimated_quarter", "-estimated_value"],
                "verbose_name": "عملية / مشروع مبرمج",
                "verbose_name_plural": "العمليات والمشاريع المبرمجة",
            },
        ),
        migrations.AddField(
            model_name="annualbudget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("state", "ميزانية الدولة (Budget de l’État)"),
                    ("wilaya", "ميزانية الولاية (Budget de Wilaya)"),
                    ("commune", "ميزانية البلدية (Budget Communal)"),
                    ("epic_epa", "ميزانية المؤسسة العمومية (EPIC / EPA)"),
                ],
                default="state",
                max_length=50,
                verbose_name="نوع الميزانية",
            ),
        ),
        migrations.AddField(
            model_name="annualbudget",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات وتوجيهات الميزانية"
            ),
        ),
        migrations.AddField(
            model_name="annualbudget",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plannedproject",
            name="ap_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="رقم رخصة البرنامج (Numéro AP)",
            ),
        ),
        migrations.AddField(
            model_name="plannedproject",
            name="estimated_quarter",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "الثلاثي الأول (Q1 - جانفي/مارس)"),
                    (2, "الثلاثي الثاني (Q2 - أفريل/جوان)"),
                    (3, "الثلاثي الثالث (Q3 - جويلية/سبتمبر)"),
                    (4, "الثلاثي الرابع (Q4 - أكتوبر/ديسمبر)"),
                ],
                default=1,
                verbose_name="الثلاثي التقديري للإطلاق",
            ),
        ),
        migrations.AddField(
            model_name="plannedproject",
            name="operation_code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="رقم العملية الميزانياتية (Code Opération)",
            ),
        ),
        migrations.AddField(
            model_name="plannedproject",
            name="planned_procedure",
            field=models.CharField(
                choices=[
                    ("open", "طلب عروض مفتوح"),
                    ("restricted", "طلب عروض محدود / قدرات دنيا"),
                    ("consultation", "استشارة بسيطة (Consultation)"),
                    ("mutual", "بالتراضي البسيط أو بعد الاستشارة"),
                ],
                default="open",
                max_length=50,
                verbose_name="الإجراء التقديري المزمع",
            ),
        ),
        migrations.AddField(
            model_name="plannedproject",
            name="procurement_nature",
            field=models.CharField(
                choices=[
                    ("works", "أشغال (Travaux)"),
                    ("supplies", "لوازم وتجهيزات (Fournitures)"),
                    ("services", "خدمات (Services)"),
                    ("studies", "دراسات واستشارات (Études)"),
                ],
                default="works",
                max_length=50,
                verbose_name="طبيعة الحاجة",
            ),
        ),
        migrations.AddField(
            model_name="plannedproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="annualbudget",
            name="sector",
            field=models.CharField(max_length=255, verbose_name="القطاع الوصي"),
        ),
        migrations.AlterField(
            model_name="annualbudget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "قيد المراجعة والاعتماد"),
                    ("approved", "معتمدة رسمياً"),
                    ("published", "منشورة بالمخطط الوطني"),
                    ("rejected", "مرفوضة"),
                ],
                default="draft",
                max_length=20,
                verbose_name="حالة المخطط",
            ),
        ),
        migrations.AlterField(
            model_name="annualbudget",
            name="total_budget",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="الغلاف المالي المخصص (دج)",
            ),
        ),
        migrations.AlterField(
            model_name="plannedproject",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_projects",
                to="procurement.annualbudget",
                verbose_name="المخطط السنوي المرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="plannedproject",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="القيمة التقديرية للحاجة (دج)",
            ),
        ),
        migrations.AlterField(
            model_name="plannedproject",
            name="expected_launch_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الإطلاق التقديري"
            ),
        ),
        migrations.AlterField(
            model_name="plannedproject",
            name="is_launched",
            field=models.BooleanField(
                default=False, verbose_name="تم التحويل إلى صفقة فعلية"
            ),
        ),
        migrations.AlterField(
            model_name="plannedproject",
            name="title",
            field=models.CharField(
                max_length=255, verbose_name="موضوع الحاجة / المشروع المبرمج"
            ),
        ),
    ]
