# Generated by Django 6.1 on 2026-08-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0040_alter_annualbudget_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedproject",
            name="planned_procedure",
            field=models.CharField(
                choices=[
                    ("open", "طلب العروض المفتوح (Appel d'offres ouvert)"),
                    (
                        "minimum_capacity",
                        "طلب العروض مع اشتراط قدرات دنيا (Capacités minimales)",
                    ),
                    ("restricted", "طلب العروض المحدود (Appel d'offres restreint)"),
                    ("contest", "المسابقة (Concours)"),
                    (
                        "negotiation",
                        "التفاوض / التراضي (Procédure négociée / Gré à gré)",
                    ),
                    ("consultation", "استشارة بسيطة (Consultation)"),
                ],
                default="open",
                max_length=50,
                verbose_name="الإجراء التقديري المزمع",
            ),
        ),
        migrations.AlterField(
            model_name="procurementauditlog",
            name="result",
            field=models.CharField(default="SUCCESS", max_length=50),
        ),
    ]
