# Generated by Django 6.1 on 2026-08-15 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0038_alter_historicaltender_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceBenchmarkEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_title",
                    models.CharField(
                        max_length=255, verbose_name="موضوع المشروع أو الخدمة"
                    ),
                ),
                ("sector", models.CharField(max_length=50, verbose_name="القطاع")),
                (
                    "estimated_min_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الحد الأدنى العادل (دج)",
                    ),
                ),
                (
                    "estimated_avg_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="السعر المرجعي المتوقع (دج)",
                    ),
                ),
                (
                    "estimated_max_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الحد الأعلى التقديري (دج)",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        default="عالية (88%)",
                        max_length=20,
                        verbose_name="مستوى الثقة الإحصائية",
                    ),
                ),
                (
                    "market_factors",
                    models.JSONField(
                        default=list, verbose_name="عوامل تسعير السوق التاريخية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقدير"
                    ),
                ),
            ],
            options={
                "verbose_name": "تقدير سعر مرجعي",
                "verbose_name_plural": "تقديرات الأسعار المرجعية",
            },
        ),
        migrations.CreateModel(
            name="AutomatedEvaluationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_summary",
                    models.JSONField(
                        default=dict, verbose_name="نتائج التقييم المقارن والتنقيط"
                    ),
                ),
                (
                    "arithmetic_errors_found",
                    models.BooleanField(
                        default=False, verbose_name="تم رصد أخطاء حسابية في العروض"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="ملاحظات ومحضر التقييم الآلي"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ جلسة التقييم"
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المشرف على الجلسة",
                    ),
                ),
                (
                    "recommended_bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommended_award",
                        to="procurement.bid",
                        verbose_name="العرض الموصى به للترسية",
                    ),
                ),
                (
                    "tender",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_evaluation_session",
                        to="procurement.tender",
                        verbose_name="الصفقة المعنية",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تقييم عروض آلية",
                "verbose_name_plural": "جلسات تقييم العروض الآلية",
            },
        ),
        migrations.CreateModel(
            name="GeneratedRFP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_title",
                    models.CharField(
                        max_length=255, verbose_name="عنوان موضوع المشروع"
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("works", "أشغال وبناء وبنية تحتية"),
                            ("supplies", "اقتناء لوازم ومعدات وتجهيزات"),
                            ("studies", "دراسات واستشارات هندسية وتقنية"),
                            ("services", "خدمات وصيانة وحراسة"),
                        ],
                        default="works",
                        max_length=20,
                        verbose_name="قطاع الصفقة",
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("open_tender", "طلب عروض مفتوح مع اشتراط قدرات دنيا"),
                            ("restricted_tender", "طلب عروض محدود"),
                            ("consultation", "استشارة بسيطة (صفقة أقل من العتبة)"),
                            ("direct_negotiation", "تراضي بعد الاستشارة"),
                        ],
                        default="open_tender",
                        max_length=30,
                        verbose_name="طبيعة الإجراء القانوني",
                    ),
                ),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="الميزانية التقديرية (دج)",
                    ),
                ),
                (
                    "execution_duration_months",
                    models.IntegerField(
                        default=6, verbose_name="مدة الإنجاز المقترحة (أشهر)"
                    ),
                ),
                (
                    "administrative_conditions",
                    models.TextField(verbose_name="الشروط الإدارية والتأهيلية"),
                ),
                (
                    "technical_specs",
                    models.TextField(verbose_name="المواصفات التقنية القياسية"),
                ),
                (
                    "scoring_criteria",
                    models.JSONField(
                        default=dict,
                        verbose_name="سلم التنقيط والتقييم التقني (100 نقطة)",
                    ),
                ),
                (
                    "required_documents",
                    models.JSONField(
                        default=list, verbose_name="قائمة الوثائق الإلزامية المطلوبة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التوليد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تعديل"),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_rfps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المصلحة المتعاقدة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسودة دفتر شروط ذكية",
                "verbose_name_plural": "مسودات دفاتر الشروط الذكية",
                "ordering": ["-created_at"],
            },
        ),
    ]
