# Generated by Django 6.1 on 2026-08-07 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0020_historicaltender_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing_field', 'حقل ناقص'), ('invalid_date', 'تاريخ غير صحيح'), ('outlier_value', 'قيمة غير منطقية'), ('inconsistent_status', 'تعارض في الحالة')], max_length=50, verbose_name='نوع المشكلة')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحقل المعني')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_issues', to='procurement.tender', verbose_name='الصفقة المرتبطة')),
            ],
            options={
                'verbose_name': 'مشكلة جودة بيانات',
                'verbose_name_plural': 'مشاكل جودة البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التنبيه')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='درجة الأهمية')),
                ('alert_type', models.CharField(help_text='مثال: تأخير، بيانات ناقصة', max_length=100, verbose_name='نوع التنبيه')),
                ('suggested_action', models.TextField(blank=True, null=True, verbose_name='الإجراء المقترح')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف')),
                ('related_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='procurement.tender', verbose_name='الصفقة المرتبطة')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'تنبيه ذكي',
                'verbose_name_plural': 'التنبيهات الذكية',
                'ordering': ['-created_at'],
            },
        ),
    ]
