# Generated by Django 6.1 on 2026-08-15 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0038_alter_historicaltender_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BidReadinessReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "readiness_percentage",
                    models.IntegerField(
                        default=85, verbose_name="نسبة اكتمال وجاهزية الملف"
                    ),
                ),
                (
                    "missing_documents",
                    models.JSONField(
                        default=list,
                        verbose_name="الوثائق الناقصة أو المنتهية الصلاحية",
                    ),
                ),
                (
                    "valid_documents",
                    models.JSONField(
                        default=list, verbose_name="الوثائق المستوفاة والصحيحة"
                    ),
                ),
                (
                    "compliance_verdict",
                    models.CharField(
                        default="جاهز للإيداع بعد استكمال وثيقة واحدة",
                        max_length=50,
                        verbose_name="القرار الإرشادي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الفحص"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المتعامل الاقتصادي",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.tender",
                        verbose_name="الصفقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير جاهزية العرض",
                "verbose_name_plural": "تقارير جاهزية العروض",
            },
        ),
        migrations.CreateModel(
            name="TenderSummaryAI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_deadlines",
                    models.JSONField(
                        default=dict, verbose_name="المهل والآجال الزمنية الجوهرية"
                    ),
                ),
                (
                    "financial_guarantees",
                    models.CharField(
                        default="كفالة تعهد بنسبة 1% من قيمة العرض",
                        max_length=255,
                        verbose_name="الكفالات والضمانات البنكية",
                    ),
                ),
                (
                    "mandatory_qualifications",
                    models.JSONField(
                        default=list, verbose_name="شروط التأهيل الإلزامية"
                    ),
                ),
                (
                    "scoring_highlights",
                    models.JSONField(
                        default=dict, verbose_name="أبرز محاور سلم التنقيط"
                    ),
                ),
                (
                    "potential_risks",
                    models.JSONField(
                        default=list, verbose_name="التنبيهات والمحاذير التعاقدية"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ توليد الملخص"
                    ),
                ),
                (
                    "tender",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summary",
                        to="procurement.tender",
                        verbose_name="الصفقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص دفتر الشروط الذكي",
                "verbose_name_plural": "ملخصات دفاتر الشروط الذكية",
            },
        ),
        migrations.CreateModel(
            name="SupplierMatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_match_score",
                    models.IntegerField(
                        default=75, verbose_name="درجة الملاءمة الإجمالية (0-100)"
                    ),
                ),
                (
                    "sector_match",
                    models.IntegerField(
                        default=80, verbose_name="تطابق التخصص والنشاط"
                    ),
                ),
                (
                    "capacity_match",
                    models.IntegerField(
                        default=70, verbose_name="تطابق التصنيف والقدرة المالية"
                    ),
                ),
                (
                    "match_reasons",
                    models.JSONField(default=list, verbose_name="أسباب ودوافع التوصية"),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(
                        default=False, verbose_name="تم إخفاؤها من طرف المورد"
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاريخ احتساب المطابقة"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المتعامل الاقتصادي",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_matches",
                        to="procurement.tender",
                        verbose_name="الصفقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "درجة مطابقة صفقة لمورد",
                "verbose_name_plural": "درجات مطابقة الصفقات للموردين",
                "ordering": ["-overall_match_score"],
                "unique_together": {("supplier", "tender")},
            },
        ),
    ]
